### ISSUE TITLE
Fix Homepage Landing component

### ISSUE THREAD

**Issue by ShivanshKumar** [kreiva-iiitv/keriva-frontend-2020#21]
@sidharth3000  I am adding the code which seems to make things better, although my code is not the complete fix, fix the spacing between navbar and landing, the spacing between "2020" text and div below it, and the gradients on "Kreiva" and "2020", also convert text to rem.

In Landing.js

           <div className="landing">
               <div>
                <img className="wave" src={wave} />
               </div>

               <div className="parent">
                   <span  className="kreiva">KREIVA</span>
                   <span className="kreiva a">2020</span>
               </div>

In Landing.css
```
.parent{
    display: flex;
    flex-direction: column;
    align-items: center;
}

.kreiva{
   background-image: linear-gradient(to bottom, #ffffff, rgba(255, 255, 255, 0.685), rgba(0, 0, 0, 0));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-size: 200px;
    font-family: Noir;
    padding-top: 19%;
    z-index: 1;
}

.a{
    font-size: 100px;
    padding: 0px;
    margin: 0px;
    margin-top: -8rem;
    background-image: linear-gradient(to bottom, #ffffff, rgba(139, 139, 139, 0.55), rgba(0, 0, 0, 0));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}
```
@pAditya198 Sir I have used margin in negative rem to overlap "2020" on "Kreiva", is that fine?

**Comment by anujpuri72** [comment]
As per the design , first of all the gradient is from "bottom to top" not form "top to bottom " and the reason why we are discouraging the use of rem  is that on smaller screen ,when  the font size will decrease the calculated rem will  not align with design instead u can use pixels and add media queries on reaching the breakpoint. Coming to your question negative margin is fine but please change units to pixels from  rem

[see this](https://vasilis.nl/nerd/dislike-rem-unit/#:~:text=The%20rem%20unit%20is%20not%20flexible%20enough.&text=A%20common%20pattern%20in%20responsive,font%2Dsizes%20remains%20the%20same)

**Comment by ShivanshKumar** [comment]
Understood

**Comment by pAditya198** [comment]
Is this issue fixed?if so, do close it
